services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: alpine/sqlite:3.51.2
    volumes:
      - db_data:/var/lib/sqlite
    healthcheck:
      test: ["NONE"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s


volumes:
  db_data: